---
title: Some Cool Sounding Buzzwords
subtitle: Less Buzzy and Somewhat More Explanaotry Subtitle
author:
  - name: Sanha Cheong
    orcid: 0000-0003-1689-0557
    email: sanha@stanford.edu
institute: |
  | Department of Physics
  | Stanford University
short-author: S. Cheong, Stanford
date: today
date-format: long
bibliography: bibliography.bib
format: 
  stanford-beamer
---

## Goals

The main goals for this slide:

- This is just to show you how this \empy{template} works
- There are two 'emphasize' functions used to highlight & italicize texts
  - '\textbackslash empy' does \empy{this} and '\textbackslash empr' does \empr{this}.
- The colors in this template is selected from the official Stanford
  Identity website: <https://identity.stanford.edu/color.html>
- Note that hyperlinks, by default, are not highlighted. Of course,
  you can change this: e.g., \empr{\href{https://github.com/sanhacheong/stanford_beamer_presentation}{https://github.com/sanhacheong/stanford\_beamer\_presentation}}

## Example 

A (hopefully) useful function in this \LaTeX-template @stanford_beamer_template is:

\begin{center}
	\textbackslash examplebox\{ExampleTitle\}\{ExampleContents\}
\end{center}

which does this:

\examplebox{Example of the Command \textbackslash examplebox}{
This is what it does. Pretty self-explanatory, isn't it?
Given the color them, I \empr{recommend} using \textbackslash empr inside of examplebox. The \textbackslash empy command does not look \empy{that} good.
}

## References