---
title: "Home"
format: 
  html:
    toc: false
---

The `stanford` Quarto theme extension provides **unofficial** Stanford University theming for Quarto documents. 

:::{.callout-note}
This extension was made for a guest lecture inside of STATS 352 to show the versatility of Quarto.
:::

## Installing

```bash
quarto use template coatless-quarto/stanford
```

This will install the extension and create an example qmd file that you can use as a starting place for your article.

## Example

For each format, there is a template file available. See:

- **RevealJS:** [RevealJS Slide Demo](demos/template-revealjs.qmd) ([Source](https://quarto.thecoatlessprofessor.com/stanford/demos/template-revealjs.html))
- **HTML:** [HTML Page Demo](demos/template-html.qmd) ([Source](https://github.com/coatless-quarto/stanford/blob/main/docs/demos/template-html.qmd))
- **Beamer:** [Slide Demo](demos/template-beamer.qmd) ([Source](https://github.com/coatless-quarto/stanford/blob/main/docs/demos/template-beamer.qmd))
- **PDF Letter of Recommendation (LOR):** [PDF LOR Demo](demos/template-pdf+lor.qmd) ([Source](https://github.com/coatless-quarto/stanford/blob/main/docs/demos/template-pdf+lor.qmd))

## Acknowledgements

### Beamer Acknowledgements 

The stanford beamer theme was obtained from:

- <https://github.com/sanhacheong/stanford-beamer-presentation>

There was a prior work attempt at packaging the theme into a Quarto extension. 

- <https://github.com/eLearningHub/quarto-stanford-presentation-starter>

